spring:
  # DB ?? ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/courtnetdb
    username: root
    password: js365@dwy5
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY}  # 환경 변수에서 가져옴
  access-token-validity-in-ms: 1800000    # 30분
  refresh-token-validity-in-ms: 604800000  # 7일